### ISSUE TITLE
why generated image letter by letter instead of token by token

### ISSUE THREAD

**Issue by deadsmither5** [wooyeolBaek/attention-map-diffusers#13]
![image](https://github.com/user-attachments/assets/3f0828cd-03ad-41a1-89a2-e6de99921c4a)

**Comment by wooyeolBaek** [comment]
@deadsmither5 
Could you try running the code committed a few days ago? If the error keeps occurring, please share the environment details and the code you executed to reproduce the issue.

**Comment by deadsmither5** [comment]
Thanks for your kind reply, after change the version to 0.1.5 in pip, the problem already solved.
